import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

const config: Config = {
  title: "Physical AI & Humanoid Robotics Textbook",
  tagline: "An educational resource on Physical AI and Humanoid Robotics",
  favicon: "img/favicon.ico",

  // Set the production url of your site here
  url: "https://nadeemsangrasi.github.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub Pages deployment, this is usually '/<projectName>/'
  baseUrl: "/humanoid-and-robotic-book/",

  // GitHub pages deployment config.
  organizationName: "nadeemsangrasi", // Usually your GitHub org/user name.
  projectName: "humanoid-and-robotic-book", // Usually your repo name.
  deploymentBranch: "gh-pages", // The branch the built static site will be pushed to
  trailingSlash: true, // Recommended for GitHub Pages

  onBrokenLinks: "throw",
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            "https://github.com/nadeemsangrasi/humanoid-and-robotic-book/tree/main/",
          // Configure the sidebar to use autogenerated structure
          routeBasePath: "/", // Serve docs at the root route
        },
        blog: false, // Disable blog functionality as per the project requirements
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    // Add the Mermaid plugin
    [
      "@docusaurus/theme-mermaid",
      {
        maxZoom: 1.5,
        theme: {
          light: "default",
          dark: "dark",
        },
      },
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: "img/docusaurus-social-card.jpg",
    navbar: {
      title: "Physical AI & Humanoid Robotics",
      logo: {
        alt: "Physical AI & Humanoid Robotics Textbook Logo",
        src: "img/logo.svg",
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "tutorialSidebar",
          position: "left",
          label: "Textbook",
        },
        {
          type: "doc",
          docId: "intro",
          position: "left",
          label: "Introduction",
        },
        {
          href: "https://github.com/nadeemsangrasi/humanoid-and-robotic-book",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Textbook",
          items: [
            {
              label: "Introduction",
              to: "/intro",
            },
          ],
        },
        {
          title: "Community",
          items: [
            {
              label: "Stack Overflow",
              href: "https://stackoverflow.com/questions/tagged/docusaurus",
            },
            {
              label: "Discord",
              href: "https://discordapp.com/invite/docusaurus",
            },
            {
              label: "Twitter",
              href: "https://twitter.com/docusaurus",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/nadeemsangrasi/humanoid-and-robotic-book",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Physical AI & Humanoid Robotics Textbook. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
